# Generated by Django 2.2.7 on 2020-06-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediablog', '0002_auto_20200626_1155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
    ]
