# Generated by Django 2.2.7 on 2020-06-26 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediablog', '0003_auto_20200626_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allreact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react', models.CharField(blank=True, choices=[('like', 'like'), ('heart', 'heart'), ('sad', 'sad'), ('haha', 'haha'), ('angry', 'angry')], max_length=10, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediablog.MediaBlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
